# Copy the config below and put it in your binary_sensors.yaml. 
# If you dont have one create one, or just download this one. 
# But be sure to update your configuration.yaml file with location of this file. 
#
# Workday Sensor - You can define multiple of these. 
- platform: workday
  country: US
  province: GA
  workdays: [mon, tue, wed, thu, fri] # Set the days of the week you want to use.
  
- platform: workday
  name: jeff_workday 
  country: US
  province: GA
  workdays: [mon, wed, fri] # Set the days of the week you want to use.

# Times Of Day: These can overlap. Go crazy. 
- platform: tod
  name: Night
  after: sunset
  before: sunrise

- platform: tod
  name: Day
  after: sunrise
  before: sunset

- platform: tod
  name: Quiet time
  after: '21:00'
  before: '06:00'

- platform: tod
  name: Morning
  after: '06:00'
  before: '08:30'

- platform: tod
  name: Midday
  after: '08:30'
  before: '17:00'

- platform: tod
  name: Evening
  after: '17:00'
  before: '21:00'

- platform: tod
  name: Overnight
  after: '18:00'
  before: '06:00'
  